### ISSUE TITLE
프로젝트 초기 구축

### ISSUE THREAD

**Issue by Hyesooo** [14-team13/acoe-backend#1]
# 목적 
- 프로젝트를 초기 세팅한다.

# 작업상세내용
- [x] ecoe --> acoe #2  
- [x]  gitIgnore에 yml 올리기
- [x] github 이슈탬플릿 생성 #8 
- [x] 서버에 java 설치 및 기본 세팅
- [x] CICD 파이프라인 작성 #4 
- [x] private key repo Git Submodules로 세팅(설정 파일은 프라이빗 레포에서 카피해서 빌드) #10 
- [x] QueryDsl 의존성 설정 수정(springboot3 호환)

# 참고사항
- github action deploy 파이프라인 이용해 dev push시 dev profile로 서버 running
![스크린샷 2023-03-11 16 02 33](https://user-images.githubusercontent.com/25236852/224470328-bf7e2e89-8c5b-4e5f-a04f-5cbec541a4f2.png)

**Comment by Hyesooo** [comment]
프로젝트명 오타 수정

**Comment by Hyesooo** [comment]
- [ ] #2

**Comment by Hyesooo** [comment]
#10 진행하며 #4 도 완료함.

resolved #4
